language: python
python:
  - "2.7"
env:
  global:
    - DJANGO_SETTINGS_MODULE=vogon.test_settings
before_script:
  - createuser -d -U postgres jars_tests;
  - psql -c 'create database jars_tests;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
