language: python
python:
  - "2.7"
before_script:
  - createuser -d -U postgres jars_tests;
  - psql -c 'create database jars_tests;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - cd jars 
  - python manage.py test
