language: python
python:
  - "2.7"
env:
  global:
    - DJANGO_SETTINGS_MODULE=jars.settings
    - BACKEND='postgres'
before_script:
  - createuser -d -U postgres jars_tests;
  - psql -c 'create database jars_tests;' -U postgres
  - pip install psycopg2
install:
  - pip install -r requirements.txt
script:
  - python -Wi manage.py test
