language: python
python:
  - "2.7"
install: 
  - pip install -r requirements.txt
before_script:
  - createuser -d -U postgres jars_tests;
  - psql -c 'create database jars_tests;' -U postgres
script: 
  - python jars/manage.py test
